<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{76ac14f2-4a0d-441a-9cc2-7827074a0a0b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	test : UDINT;
	testbool : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[test := test + 1;
testbool := true;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>